- name: Generate my.cnf for each node
  template:
    src: ./data/my.cnf.j2
    dest: "{{ data_dir }}/node{{ item }}/my.cnf"
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Prepare docker container and install Percona Server for MySQL
  include_tasks: ./tasks/prepare_install_ps.yml
